version: "3.9"

services:
  app:
    image: mcr.microsoft.com/playwright/python:v1.43.0  # Use uma imagem Playwright disponível
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    expose:
      - "8000"
    networks:
      - web
    restart: always

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
